### ISSUE TITLE
cdk deploy "*-test"

### ISSUE THREAD

**Issue by nexuswebstudio** [rfpedrosa/aws-cdk#10]
Cannot read property 'split' of undefined
Subprocess exited with error 1

**Comment by rfpedrosa** [comment]
in which stack? please share the stack trace as well?

**Comment by nexuswebstudio** [comment]
I am just deploying as is for now, I have just changed the account number in cdk.json
I also tried cdk bootstarp same error coming

**Comment by rfpedrosa** [comment]
- "I am just deploying as is, for now, I have just changed the account number in cdk.json" -> [that should be enough to bootstrap and trigger a deployment](https://github.com/rfpedrosa/aws-cdk#getting-started)
- Please provide the stacktrace. I just tested this last week with the latest versions of aws cdk and nodejs so it makes me feel that is something in your setup (although the code can always be improved with, for example, better error messages)

**Comment by nexuswebstudio** [comment]
ahmad-hassan@ahmadhassan-ThinkPad-E15-Gen-2:~/Documents/aws-cdk$ npm run build & npx jest
[1] 12746

> aws-cdk-rpedrosa-template@0.1.0 build /home/ahmad-hassan/Documents/aws-cdk
> tsc

 PASS  test/network.test.ts (9.307 s)
 PASS  test/storage.test.ts (9.355 s)
 PASS  test/authentication.test.ts (9.413 s)
 PASS  test/database.test.ts (9.477 s)
 PASS  test/compute.test.ts (9.608 s)

Test Suites: 5 passed, 5 total
Tests:       13 passed, 13 total
Snapshots:   0 total
Time:        9.851 s, estimated 11 s
Ran all test suites.
ahmad-hassan@ahmadhassan-ThinkPad-E15-Gen-2:~/Documents/aws-cdk$ ^[[B^[[A^[[A^[[ 

[1]+  Done                    npm run build
ahmad-hassan@ahmadhassan-ThinkPad-E15-Gen-2:~/Documents/aws-cdk$ sudo cdk deploy "*-test"
Cannot read property 'split' of undefined
Subprocess exited with error 1
ahmad-hassan@ahmadhassan-ThinkPad-E15-Gen-2:~/Documents/aws-cdk$ sudo cdk deploy "*-test"
[sudo] password for ahmad-hassan: 
Cannot read property 'split' of undefined
Subprocess exited with error 1
ahmad-hassan@ahmadhassan-ThinkPad-E15-Gen-2:~/Documents/aws-cdk$ cdk deploy —-profile hippa-test 64bit Amazon Linux 2 v3.1.2 running Python 3.7
Cannot read property 'split' of undefined
Subprocess exited with error 1

**Comment by nexuswebstudio** [comment]
Sorry for inconvenience, that was issue with my node.js version and also I didn't updated the callback urls earlier.

**Comment by rfpedrosa** [comment]
no worries. I'm glad that you get it working :)
